name: Pipeline

on:
  push:
    branches:
    tags:
  pull_request:
    branches:

jobs:
  tox:
    runs-on: ubuntu-latest
    environment: test
    strategy:
      matrix:
        python-version: [ "py310", "py311", "py312", "py313" ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup Poetry
        uses: ./.github/actions/setup-poetry
      - name: Tox
        id: tox
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          source .venv/bin/activate
          echo "Running tox with python version $PYTHON_VERSION"
          tox -e "$PYTHON_VERSION"

  pytest:
    runs-on: ubuntu-latest
    environment: test
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Poetry
        uses: ./.github/actions/setup-poetry
      - name: Run Pytest
        id: pytest
        run: |
          source .venv/bin/activate
          pytest tests/
